{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "releaseway.fullname" . }}
  labels:
    {{- include "releaseway.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.secrets.accessKeyId | quote }}
  SECRET_ACCESS_KEY: {{ .Values.secrets.secretAccessKey | quote }}
  TOKEN: {{ .Values.secrets.token | quote }}
{{- end }}
